# @no-redirect

GET http://127.0.0.1:8080/api/json2

####

GET http://127.0.0.1:8080/api/json

####

GET http://127.0.0.1:8080/api/auth/json

####

GET http://127.0.0.1:8080/api/main-on

####

GET http://127.0.0.1:8080/api/main

####

GET http://127.0.0.1:8080/api/all

####

GET  http://127.0.0.1:8080/all

